[lint]
select = ["E", "F", "W", "I"]
ignore = []

[lint.per-file-ignores]
"__init__.py" = ["F401"]

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

# Move exclude to the top level
exclude = [
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "build",
    "dist"
]
